# Generated by Django 4.2.4 on 2023-08-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courses_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='courses',
            new_name='course',
        ),
    ]
